moment.lang 'en',
  relativeTime:
    future: "in %s"
      past: "%s"
      s:  "just now"
      m:  "a min ago"
      mm: "%d min ago"
      h:  "an hr ago"
      hh: "%d hrs ago"
      d:  "a day ago"
      dd: "%d days ago"
      M:  "a month ago"
      MM: "%d months ago"
      y:  "a year ago"
      yy: "%d years ago"
