# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  shell_commands = [
    "echo '#{`cat ~/.ssh/id_rsa.pub`}' | sudo tee -a /root/.ssh/authorized_keys"
  ]

  config.vm.provision "shell",
    inline: shell_commands.join("; "),
    privileged: false


  config.vm.define "firebrick" do |named_vm|
    named_vm.vm.box = "ubuntu/trusty64"
    named_vm.vm.network "private_network", ip: "33.33.33.10"
  end

end
