language: erlang
otp_release:
   - R16B

before_install:
  - mkdir $HOME/src
  - git clone https://github.com/elixir-lang/elixir.git $HOME/src/elixir
  - cd $HOME/src/elixir && git checkout $ELIXIR_VERSION && make clean test && cd -

env:
  - PATH=$PATH:$HOME/src/elixir/bin/ ELIXIR_VERSION=v0.11.2

install: mix deps.get
script:  mix test
