---
- name: "clone project"
  git: repo="{{project_repo}}" dest="{{project_path}}"
  remote_user: "{{run_as_user}}"


- name: "install tool versions using asdf"
  command: 'bash -lc "asdf install"'
  remote_user: "{{run_as_user}}"
  args:
    chdir: "{{project_path}}"


- name: "fetch project dependencies"
  command: 'bash -lc "mix deps.get"'
  remote_user: "{{run_as_user}}"
  args:
    chdir: "{{project_path}}"
    environment: "MIX_ENV={{ mix_env }}"


- name: "run database migrations"
  command: 'bash -lc "mix ecto.migrate"'
  remote_user: "{{run_as_user}}"
  args:
    chdir: "{{project_path}}"
    environment: "MIX_ENV={{ mix_env }}"
