---
- hosts: firebrick-servers
  remote_user: root
  vars:
    deployer: "deployer"
    project_repo: https://github.com/HashNuke/firebrick.git
    project_path: "/home/{{deployer}}/projects/firebrick"
    project_version: "master"
    mix_env: "prod"

    #TODO decide using mix_env or rails_env or node_env
    database_name: "firebrick-{{mix_env}}"

    frontend_path: "{{project_path}}/frontend"


  roles:
    - common
    - {role: "deployer-user", user_to_create: "{{deployer}}" }
    - pip
    - {role: "postgres", database_owner: "{{deployer}}" }
    - {role: "asdf", run_as_user: "{{deployer}}" }
    - {role: "elixir-project", run_as_user: "{{deployer}}" }
    - {role: "frontend", run_as_user: "{{deployer}}" }
    # TODO monit
    # TODO logrotate


    # - name: "copy monit config"
    #   template: src="firebrick.monit.j2" dest="/etc/monit/conf/firebrick.monit"


    # - name: start monit
    #   service: name=monit state=started enabled=yes

    # - name: "copy logrotate config"
