---
- hosts: firebrick-servers
  remote_user: root
  vars:
    deployer: "deployer"
    project_path: "/home/{{deployer_user}}/projects/firebrick"
    project_version: "master"
    mix_env: "prod"

  tasks:
    - name: "add postgres repository"
      apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"


    - name: "add postgres repository key"
      apt_key: url="https://www.postgresql.org/media/keys/ACCC4CF8.asc"


    - name: "install system packages"
      apt: name="{{ item }}" update_cache=yes
      with_items:
        - git
        - curl
        - wget
        - python-apt
        - automake
        - autoconf
        - libreadline-dev
        - libncurses-dev
        - libssl-dev
        - libyaml-dev
        - libxslt-dev
        - libffi-dev
        - libtool
        - unixodbc-dev
        - postgresql-9.4
        - logrotate
        - monit


    - name: "create deployer user {{deployer}}"
      user: name="{{deployer}}" shell=/bin/bash


    - name: "read authorized keys from root user"
      command: "cat ~/.ssh/authorized_keys"
      register: "root_authorized_keys"


    - name: "create .ssh dir for {{deployer}}"
      file: path="/home/{{deployer}}/.ssh" state=directory


    - name: "copy authorized keys to deployer user"
      shell: "echo '{{root_authorized_keys.stdout}}' > /home/{{deployer}}/.ssh/authorized_keys"


    - name: "chown the authorized_keys file"
      file: path="/home/{{deployer}}/.ssh" recurse=yes mode=0700 owner="{{deployer}}"


    - name: "install asdf"
      git: repo="https://github.com/HashNuke/asdf.git" dest="~/.asdf"
      remote_user: "{{deployer}}"


    - name: "source asdf in bashrc"
      lineinfile: dest="~/.bash_profile" create=yes line="source ~/.asdf/asdf.sh"
      remote_user: "{{deployer}}"


    - name: "add asdf plugins"
      command: "bash -lc 'asdf plugin-add {{item}} https://github.com/HashNuke/asdf-{{item}}.git'"
      with_items:
        - nodejs
        - erlang
        - elixir
      remote_user: "{{deployer}}"


    - name: "ensure projects directory"
      file: path="~/projects" state=directory
      remote_user: "{{deployer}}"


    - name: "clone firebrick project"
      git: repo="https://github.com/HashNuke/firebrick.git" dest="~/projects/firebrick"
      remote_user: "{{deployer}}"


    - name: "install erlang, elixir & nodejs using asdf"
      command: 'bash -lc "asdf install"'
      remote_user: "{{deployer}}"

    - name: "create database"
      postgresql_db: name="firebrick-prod" encoding='UTF-8'
      remote_user: "{{deployer}}"


    - name: "fetch project dependencies"
      command: 'bash -lc "mix deps.get"'
      remote_user: "{{deployer}}"
      args:
        chdir: "{{project_dir}}"
        environment: "MIX_ENV={{ mix_env }}"


    - name: "run database migrations"
      command: 'bash -lc "mix ecto.migrate"'
      remote_user: "{{deployer}}"
      args:
        chdir: "{{project_path}}"
        environment: "MIX_ENV={{ mix_env }}"


    - name: "install frontend dependencies"
      command: 'bash -lc "npm install --production"'
      remote_user: "{{deployer}}"
      args:
        chdir: "{{project_path}}/frontend"


    - name: "build frontend"
      command: 'bash -lc "npm run build -prod"'
      remote_user: "{{deployer}}"
      args:
        chdir: "{{project_path}}/frontend"


    # - name: "copy monit config"
    #   template: src="firebrick.monit.j2" dest="/etc/monit/conf/firebrick.monit"


    # - name: start monit
    #   service: name=monit state=started enabled=yes

    # - name: "copy logrotate config"
